### ISSUE TITLE
CdbReaderThread Blocks Ctrl + C 

### ISSUE THREAD

**Issue by goldstar611** [debugregister/pycdb#15]
I have learned that if you make the CdbReaderThread class a "daemon thread", it greatly increases the ability of [Ctrl] + [C] to work.

Is there any issue you see with making that the default or providing an option when instantiating PyCdb?

**Comment by fishstiqz** [comment]
No issue with that! I remember toying this a bit in the past. Only thing I
would suggest testing is to make sure that exits work as expected.

**Comment by goldstar611** [comment]
In preparation for the incoming python3 branch I wanted to point out that I think the ability of [Ctrl] + [C] may have been diminished by lines.

https://github.com/fishstiqz/pycdb/blob/ba1034200b22676f7af6bc739c646ae8ff424894/pycdb/pycdb.py#L255
and
https://github.com/fishstiqz/pycdb/blob/ba1034200b22676f7af6bc739c646ae8ff424894/pycdb/pycdb.py#L261

These fixes will be in the branch.
