### ISSUE TITLE
Python 3 - Super Slow

### ISSUE THREAD

**Issue by goldstar611** [debugregister/pycdb#16]
I love pycdb and have had great success with it but recently tried to move it to python 3 and found that it was horribly slow.

My first attempt was at Subprocess.Popen() adding text=True  to the list of named parameters so we can bypass Python3's bytes vs str differences. Something that used to take 3 seconds now takes about 30 seconds!

Has anyone else seen this?

**Comment by fishstiqz** [comment]
@goldstar611 thanks for the report. Full disclosure: I haven't used this project in a few years now. I may or may not have time to actually take a look at python 3 migration and performance. If you would like to figure it out I'm happy to take a pull request.

**Comment by goldstar611** [comment]
Still using pycdb :) and I wanted to follow up that `Subprocess.Popen(..., text=True)` wasn't providing good enough speed so we use `.decode("ISO-8859-1")` in two spots in the `run` function. If you're ok with a larger PR that has some PEP8, linting fixes and such, I could finally send that PR. We've been on python3 for some time now since I wrote this issue and I'd say it's stable.

**Comment by goldstar611** [comment]
also, thank you for adding the MIT license :)

**Comment by fishstiqz** [comment]
You're welcome. And thanks for doing all the py3 work on it. I'm very happy to see it still being useful, I used it a lot back when i was actively developing it. I've added you as a contributor. Feel free to do whatever you wish to the project

**Comment by goldstar611** [comment]
Hi I appreciate the collaboration opportunity. I'm going to add a python3 branch and send a PR.
