### ISSUE TITLE
Add timeout to read_to_prompt

### ISSUE THREAD

**Issue by fishstiqz** [debugregister/pycdb#9]
It would be quite handy to have a timeout associated with the _read_to_prompt_ call. If the timeout is reached before a prompt is encountered, control would be returned back to the caller. However, at this point the debugger is not able to be interacted with and thus subsequent operations requiring writing to the pipe should raise some exception indicating this. 

Perhaps even wrap the _read_to_prompt_ call with a function named something like _wait_for_event_ to be more clear.

**Comment by ASKobayashi** [comment]
Resolved in 276211e
